port: "8080"
frontend_url: "http://localhost:3000"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  name: "viandas_db"
  sslmode: "disable"

resend:
  api_key: ""
  from_email: "onboarding@resend.dev"
