### Variables
@baseUrl = http://localhost:8080
@token = <pega_tu_token_aqui>

### ─────────────────────────────
### AUTH
### ─────────────────────────────

### Register — crear usuario ADMIN
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@admin.com",
  "password": "123456",
  "role": "ADMIN"
}

###

### Register — crear usuario EMPLOYEE
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Empleado",
  "email": "empleado@viandas.com",
  "password": "123456",
  "role": "EMPLOYEE"
}

###

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "123456"
}

###

### Me — perfil del usuario autenticado
GET {{baseUrl}}/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ0MjJhODEtNTNhNi00NmMwLWJiYTEtNTY0NzllYjg5NGFjIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3ODE1NDI4NDMsImlhdCI6MTc4MTQ1NjQ0M30.qClA-gz8vmXJ1bHUwrzOcu-CTsF9t2sMm0Wc8VX-i68

###
