### Variables
@baseUrl = http://localhost:8080
@token = <pega_tu_token_aqui>

### ─────────────────────────────
### AUTH
### ─────────────────────────────

### Register — crear usuario ADMIN
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@admin.com",
  "password": "123456",
  "role": "ADMIN"
}

###

### Register — crear usuario EMPLOYEE
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Empleado",
  "email": "empleado@viandas.com",
  "password": "123456",
  "role": "EMPLOYEE"
}

###

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "123456"
}

###

### Me — perfil del usuario autenticado
GET {{baseUrl}}/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTJjMWFmMDYtYzMxZS00YWUzLThiZTgtMWI5ZDIxZmE3OWQ5IiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3ODE1NDgwMTksImlhdCI6MTc4MTQ2MTYxOX0.E87BFndaahsIRBXMfy5pwkAUfzTjqYDpUKLS0tQuk38

###
