### Variables
@baseUrl = http://localhost:8080
@token = <pega_tu_access_token_aqui>
@refreshToken = <pega_tu_refresh_token_aqui>

### ─────────────────────────────
### AUTH
### ─────────────────────────────

### Register — crear usuario ADMIN
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@admin.com",
  "password": "123456",
  "role": "ADMIN"
}

###

### Register — crear usuario EMPLOYEE
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Empleado",
  "email": "empleado@viandas.com",
  "password": "123456",
  "role": "EMPLOYEE"
}

###

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "123456"
}

###

### Me — perfil del usuario autenticado
GET {{baseUrl}}/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWRmYjYxY2EtYTA2NC00YjBjLWEzNGEtMWFiYTlhMWViNjg1IiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3ODE1ODA3OTQsImlhdCI6MTc4MTU3OTg5NH0.b56QZD8IbezkisFGPPixQIurVUuKVjDgUGq1G8IWcP0

###

### Refresh — obtener nuevo access_token y refresh_token
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refresh_token": "{{refreshToken}}"
}

###

### Logout — revocar refresh_token
POST {{baseUrl}}/auth/logout
Content-Type: application/json

{
  "refresh_token": "{{refreshToken}}"
}

###
