### Variables
@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTJjMWFmMDYtYzMxZS00YWUzLThiZTgtMWI5ZDIxZmE3OWQ5IiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3ODE1NDgwMTksImlhdCI6MTc4MTQ2MTYxOX0.E87BFndaahsIRBXMfy5pwkAUfzTjqYDpUKLS0tQuk38
@customerId = <pega_el_id_del_cliente>

### ─────────────────────────────
### CUSTOMERS
### ─────────────────────────────

### Crear cliente sin teléfono ni dirección (ADMIN)
POST {{baseUrl}}/customers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Aluar",
  "type": "COMPANY",
  "phone": "2804207744",
  "address": "Ruta 4"
}

###

### Crear cliente (ADMIN)
POST {{baseUrl}}/customers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Aluar",
  "type": "COMPANY",
  "phone": "111222333",
  "address": "Av. Corrientes 123, CABA"
}

###

### Crear cliente persona (ADMIN)
POST {{baseUrl}}/customers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Juan Pérez",
  "type": "PERSON",
  "phone": "444555666",
  "address": "Calle Falsa 456"
}

###

### Listar todos los clientes
GET {{baseUrl}}/customers
Authorization: Bearer {{token}}

###

### Obtener cliente por ID
GET {{baseUrl}}/customers/one?customerId=a07d734c-8f6c-456e-aad7-656ac9e749b6
Authorization: Bearer {{token}}

###

### Actualizar cliente (ADMIN)
PUT {{baseUrl}}/customers/{{customerId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Empresa A Actualizada",
  "type": "COMPANY",
  "phone": "999888777",
  "address": "Nueva dirección 789"
}

###

### Eliminar cliente (ADMIN)
DELETE {{baseUrl}}/customers/{{customerId}}
Authorization: Bearer {{token}}

###
