### Variables
@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiODIzYmViODQtMzcwNS00OTE0LWI5NmMtNDZhOWZhMDc3M2E4IiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3ODE1ODA4NjIsImlhdCI6MTc4MTQ5NDQ2Mn0.ci6rJf0wiotVJNpfxhNE9P_L_sntrOdXd8l6s2gXOWU
@deliveryId = <pega_el_id_del_delivery>

### ─────────────────────────────
### DELIVERIES
### ─────────────────────────────

### Crear delivery (ADMIN)
POST {{baseUrl}}/deliveries
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Juan Fernandez",
  "phone": "2804203212"
}

###

### Crear otro delivery (ADMIN)
POST {{baseUrl}}/deliveries
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Pedro"
}

###

### Listar todos los deliveries
GET {{baseUrl}}/deliveries
Authorization: Bearer {{token}}

###

### Obtener delivery por ID
GET {{baseUrl}}/deliveries/one?deliveryId=6c37450c-9fb3-4e7f-991f-6a5a4808418f
Authorization: Bearer {{token}}

###

### Actualizar delivery (ADMIN)
PUT {{baseUrl}}/deliveries/{{deliveryId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Juan P.",
  "phone": "2804207744",
  "active": true
}

###

### Desactivar delivery (ADMIN)
PUT {{baseUrl}}/deliveries/{{deliveryId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Juan P.",
  "phone": "2804207744",
  "active": false
}

###

### Eliminar delivery (ADMIN)
DELETE {{baseUrl}}/deliveries/{{deliveryId}}
Authorization: Bearer {{token}}

###
