### Variables
@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWRmYjYxY2EtYTA2NC00YjBjLWEzNGEtMWFiYTlhMWViNjg1IiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3ODE4MjMyMDUsImlhdCI6MTc4MTgyMjMwNX0.4bciJKNXQN4DAV_j6TMuEJYG41WbZiPpW-qRQ6iMIgA
@deliveryId = <pega_el_id_del_delivery>

### ─────────────────────────────
### DELIVERIES
### ─────────────────────────────

### Crear delivery (ADMIN)
POST {{baseUrl}}/deliveries
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Diego Perez",
  "phone": "2804203212"
}

###

### Crear otro delivery (ADMIN)
POST {{baseUrl}}/deliveries
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Pedro"
}

###

### Listar todos los deliveries
GET {{baseUrl}}/deliveries
Authorization: Bearer {{token}}

###

### Listar deliveries paginados
GET {{baseUrl}}/deliveries?page=1&limit=10
Authorization: Bearer {{token}}

###

### Listar deliveries filtrando por nombre (?q=)
GET {{baseUrl}}/deliveries?q=juan
Authorization: Bearer {{token}}

###

### Obtener delivery por ID
GET {{baseUrl}}/deliveries/one?deliveryId=6c37450c-9fb3-4e7f-991f-6a5a4808418f
Authorization: Bearer {{token}}

###

### Actualizar delivery (ADMIN)
PUT {{baseUrl}}/deliveries
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{deliveryId}}",
  "name": "Juan P.",
  "phone": "2804207744",
  "active": true
}

###

### Desactivar delivery (ADMIN)
PUT {{baseUrl}}/deliveries
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{deliveryId}}",
  "name": "Juan P.",
  "phone": "2804207744",
  "active": false
}

###

### Eliminar delivery (ADMIN)
DELETE {{baseUrl}}/deliveries
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{deliveryId}}"
}

###
